@startuml

class ChaincodeAction {
	Results []byte
	Events []byte
	Response *Response
	ChaincodeId *ChaincodeID
	TokenExpectation     *token.TokenExpectation
}

note top of ChaincodeAction : Result 就是 rwset

class ChaincodeEvent{
	ChaincodeId string
	TxId string
	EventName string
	Payload []byte
}

ChaincodeAction <-- ChaincodeEvent
@enduml