@startuml

class MSPPrincipal  {
	+ PrincipalClassification
	+ Principal []byte
}

enum MSPPrincipal_Classification {
	MSPPrincipal_ROLE
	MSPPrincipal_ORGANIZATION_UNIT
	MSPPrincipal_IDENTITY
	MSPPrincipal_ANONYMITY
	MSPPrincipal_COMBINED
}
MSPPrincipal *-- MSPPrincipal_Classification

class MSPRole {
	MspIdentifier string
	Role MSPRole_MSPRoleType
}

enum MSPRole_MSPRoleType {
	MSPRole_MEMBER
    MSPRole_ADMIN
    MSPRole_CLIENT
    MSPRole_PEER
}

MSPRole *-- MSPRole_MSPRoleType
note "MSPRole是 MSPPrincipal中的一个内容"  as c1
c1 .. MSPRole
c1 .. MSPPrincipal

@enduml